- hosts: localhost
  vars:
    cloud_provider: azure
    domain: "{{ fqdn }}"
    targets:
      - rna
      #- tekton
      #- gitlab
  vars_files:
    - vars/eagle.yml
    - vars/dns.yml
    - vars/ssh.yml
    - vars/azure.yml
    - vars/credentials.yml
    - vars/sentry.yml
  tasks:
    - include_tasks: tasks/burn.yml