- hosts: localhost
  vars:
    cloud_provider: azure
    domain: "{{ fqdn }}"
    # why does this query return an array?  I have literally no idea.  [jvf]
    slug: "{{ query('community.general.random_string', upper=false, numbers=true, special=false)[0] }}"
  vars_files:
    - vars/eagle.yml
    - vars/dns.yml
    - vars/ssh.yml
    - vars/azure.yml
    - vars/github.yml
    - vars/credentials.yml
    - vars/sentry.yml

  tasks:
  - include_role:
      name: bigfleet.eagle
    vars:
      phase: 0
      eagle_params:
        azure:
          resource_group_name: "eagle-{{azure_location}}"
          dns_resource_group_name: "eagle-dns-{{azure_location}}"
        kv:
          key_name: eaglespcreds
          vault_name: "{{ eagle_kv_vault_name }}"
        issuer_provider: "{{ issuer_provider | default('letsencrypt') }}"

  - include_role:
      name: bigfleet.eagle
    vars:
      phase: wiring
      eagle_params:
        azure:
          resource_group_name: "eagle-{{azure_location}}"
          dns_resource_group_name: "eagle-dns-{{azure_location}}"

  - include_role:
      name: bigfleet.eagle
      tasks_from: gitops_deploy.yml
    vars:
      eagle_params:
        azure:
          resource_group_name: "eagle-{{azure_location}}"
          dns_resource_group_name: "eagle-dns-{{azure_location}}"
        identity_name: flux2-sops-reader
        # flux2:
        #   extra_args:
        #     - --personal # in case you are hosting personally
    when: false