- hosts: localhost
  vars:
    cloud_provider: gcp
    domain: "{{ fqdn }}"
    slug: "{{ query('community.general.random_string', upper=false, numbers=true, special=false)[0] }}"
  vars_files:
    - vars/eagle.yml
    - vars/dns.yml
    - vars/ssh.yml
    - vars/gcp.yml
    - vars/credentials.yml
    - vars/sentry.yml
  tasks:
  - include_role:
      name: bigfleet.eagle
    vars:
      phase: 0
      eagle_params:
        gcp:
          resource_group_name: "eagle-{{gcp_location}}"
          dns_resource_group_name: "eagle-dns-{{gcp_location}}"
          location: "{{gcp_location}}"
          tags: "{{ gcp_common_tags }}"
        kv:
          key_name: eaglespcreds
          vault_name: "{{ eagle_kv_vault_name }}"
        issuer_provider: "{{ issuer_provider | default('letsencrypt') }}"

  - include_role:
      name: bigfleet.gitlab
    vars: 
      gitlab_params:
        issuer_provider: "{{ issuer_provider | default('letsencrypt') }}"
        gcp:
          ad_application_name: Morgan Stanley iP2P Gitlab
          auth_secret_name: "gitlab-auth-secret-{{eagle_mark}}"
          resource_group_name: "eagle-{{gcp_location}}"
          dns_resource_group_name: "eagle-dns-{{gcp_location}}"
        agent_pool_profile: himem
        dns: 
          full_name: "{{dns_prefix}}"
          registrar: dnsimple
        kv:
          enabled: true
          vault_name: "{{ eagle_kv_vault_name }}"
        gitlab_admin_email: john.keene@endava.com
        tags: "{{ az_common_tags }}"
        user_list: 
          - name: "John Keene"
            is_admin: true
            email: john.keene@levvel.io
            username: john.keene
          - name: "Jim Van Fleet"
            is_admin: false
            email: jim.van.fleet@levvel.io
            username: james.vanfleet
        domain_allow_list:
          - endava.com
          - levvel.io
        create_users: true
      cert_email: john.keene@endava.com
      k8s_namespace: gitlab
    when: false