
- include_role:
    name: bigfleet.eagle
    tasks_from: load_rna.yml

- include_tasks: "burn/{{cloud_provider}}.yml"

- name: "Delete the {{ eagle_gitops_repo_name }} repository"
  community.general.github_repo:
    access_token: "{{ github_token }}"
    name: "{{ eagle_gitops_repo_name }}"
    organization: "{{ scm_config.organization }}"
    state: absent
  when: "'rna' is in targets"

- name: "Delete the primary {{ eagle_rna.name }} repository"
  community.general.github_repo:
    access_token: "{{ github_token }}"
    name: "{{ eagle_rna.name }}"
    organization: "{{ scm_config.organization }}"
    state: absent
  when: "'rna' is in targets"

- name: Delete the fluxing repos
  community.general.github_repo:
    access_token: "{{ github_token }}"
    name: "{{ item.name }}"
    organization: "{{ scm_config.organization }}"
    state: absent
  when: "'rna' is in targets"
  loop: "{{ eagle_rna.applications }}"